# Generated by Django 4.1.7 on 2023-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0002_rename_category_categories_rename_products_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='to be filled', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
