# Generated by Django 4.1.7 on 2023-02-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0006_product_product_description_product_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
