# Generated by Django 4.1.7 on 2023-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0007_remove_product_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
