# Generated by Django 4.1.7 on 2023-02-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0010_product_image_alter_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
