# Generated by Django 4.1.7 on 2023-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0011_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
