# Generated by Django 4.1.7 on 2023-03-01 15:49

import admin_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0013_alter_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.AddField(
            model_name='product',
            name='identification',
            field=models.IntegerField(default=admin_products.models.generate_product_id, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
