# Generated by Django 4.1.7 on 2023-03-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0016_product_image_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Image',
        ),
    ]
