# Generated by Django 4.1.7 on 2023-03-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0018_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
