# Generated by Django 4.1.7 on 2023-03-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0020_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_color',
            name='color_name',
        ),
        migrations.AddField(
            model_name='product_color',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product_Variant',
        ),
        migrations.AddField(
            model_name='product_color',
            name='color',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_products.colors'),
            preserve_default=False,
        ),
    ]
