# Generated by Django 4.1.7 on 2023-03-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0022_product_variant_remove_product_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Product_Variant',
        ),
    ]
