# Generated by Django 4.1.7 on 2023-03-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0024_product_product_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_sample',
        ),
    ]
