# Generated by Django 4.1.7 on 2023-03-05 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
