# Generated by Django 4.1.7 on 2023-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(default='notprovied', upload_to='categories'),
            preserve_default=False,
        ),
    ]
