# Generated by Django 4.1.7 on 2023-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=10, null=True, verbose_name='username'),
        ),
    ]
