# Generated by Django 4.1.7 on 2023-02-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0003_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=250, unique=True, verbose_name='email address'),
        ),
    ]
