# Generated by Django 4.1.7 on 2023-02-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0005_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
