# Generated by Django 4.1.7 on 2023-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0006_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
