# Generated by Django 4.1.7 on 2023-02-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0008_mobile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
