# Generated by Django 4.1.7 on 2023-03-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0011_alter_customuser_phone_alter_customuser_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_address',
        ),
    ]
