# Generated by Django 4.1.7 on 2023-03-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0013_customuser_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
