# Generated by Django 4.1.7 on 2023-03-01 07:08

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_id', models.IntegerField(default=user_profile.models.generate_order_id, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
