# Generated by Django 4.1.7 on 2023-03-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_default_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
