# Generated by Django 4.1.7 on 2023-03-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Default_Address',
        ),
    ]
