# Generated by Django 4.1.7 on 2023-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_delete_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='contact_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_address',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
