# Generated by Django 4.1.7 on 2023-03-11 15:58

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(default=cart.models.generate_cart_id, unique=True),
        ),
    ]
