# Generated by Django 4.1.7 on 2023-03-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem2_cart2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='cartitem2',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem2',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cart2',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CartItem2',
        ),
    ]
