# Generated by Django 4.1.7 on 2023-03-11 15:58

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_cart_id_cartitem2_cart2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem2',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem2',
            name='variant',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(default=cart.models.generate_cart_id, unique=True),
        ),
        migrations.DeleteModel(
            name='Cart2',
        ),
        migrations.DeleteModel(
            name='CartItem2',
        ),
    ]
