# Generated by Django 4.1.7 on 2023-03-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_cart_id_cartitem2_cart2'),
        ('cart', '0003_remove_cartitem2_cart_remove_cartitem2_variant_and_more'),
        ('cart', '0004_initial'),
    ]

    operations = [
    ]
