# Generated by Django 4.1.7 on 2023-03-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_merge_20230312_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem2',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem2',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Cart2',
        ),
        migrations.DeleteModel(
            name='CartItem2',
        ),
    ]
