# Generated by Django 4.1.7 on 2023-02-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_img',
            field=models.ImageField(blank=True, null=True, upload_to='brand'),
        ),
    ]
